Feat/ethers v6
RauppRafael/ryze-ethereum pull request #2
Opened 2023-05-27 01:16 UTC by RauppRafael

2023-05-27 19:13 UTC, matheus-pissaia commented on src/classes/WalletProvider/WalletProvider.ts
> +        return parseChain(chain) as Chain
`parseChain` should return a `Chain` type without the needing of enforcing with `as`

2023-05-27 19:13 UTC, matheus-pissaia commented on src/classes/WalletProvider/WalletProvider.ts
> +            // TODO handle disconnect event
Are you going to resolve this TODO in the current PR?

2023-05-27 19:15 UTC, matheus-pissaia commented on src/chain/chains.ts
>          return chain as Chain
Also, you can reuse this method in other places and maybe add a second parameter like a custom chain array

2023-05-28 17:33 UTC, RauppRafael commented on src/classes/WalletProvider/WalletProvider.ts
> +            // TODO handle disconnect event
no need for this event

2023-05-29 14:02 UTC, iankressin requested changes

2023-05-29 15:23 UTC, iankressin approved these changes

2023-05-29 15:25 UTC, iankressin approved these changes

2023-05-29 17:05 UTC, matheus-pissaia approved these changes

2023-06-30 16:36 UTC, merged