[FIX] reconnect not persisting wallet application
RauppRafael/ryze-ethereum pull request #9
Opened 2023-06-08 20:22 UTC by RauppRafael

2023-06-09 20:37 UTC, matheus-pissaia commented on src/classes/WalletInfo.ts
> +
I would probably use the `z` notation here, since its more concise and gives a clear insight about where those method comes from :wink:

2023-06-10 00:05 UTC, matheus-pissaia approved these changes

2023-06-12 16:36 UTC, iankressin requested changes

2023-06-12 16:36 UTC, iankressin commented on src/classes/WalletInfo.ts
> +import { object, string, boolean, nativeEnum } from 'zod'
since object, string and boolean are typescript keywords/types, I'd suggest to use an import alias to avoid misinterpretations

```ts
import { object as zodObject, string as zodString, ... } from 'zod'
```
 
Or even
```ts
import { object as zObject, string as zString, ... } from 'zod'
```

2023-06-12 16:44 UTC, merged